# Site settings
author: Richard Frost
title: I'm a Teapot
header-img: img/home-bg.png
email: frost.rchrd@gmail.com
copyright_name: Richard Frost
description: > # this means to ignore newlines until "baseurl:"
  determined to brew coffee
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Richard-Frost

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
